name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (<MAJOR>.<MINOR>)'
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: v${{ inputs.release-version }}
      WINDOWS_RELEASE_APPLICATION_ZIP: navme-lib_windows_v${{ inputs.release-version }}.zip

    steps:
      - uses: actions/checkout@v3

      - name: Download built library (Windows)
        uses: actions/download-artifact@v3
        with:
          name: built-library-windows
          path: built-library-windows

      - name: Create include directory
        run: |
          mkdir built-library-windows/include
          mkdir built-library-windows/include/XPlane-navdata-parser

      - name: Copy header files
        run: |
          cp src/*.h built-library-windows/include
          cp src/XPlane-navdata-parser/*.h built-library-windows/include/XPlane-navdata-parser

      
      - name: Create release plugin zip (Windows)
        run: |
          cd built-library-windows
          zip -r ../${WINDOWS_RELEASE_APPLICATION_ZIP} .

      - name: Create draft release
        run: |
          gh release create \
            --draft \
            --title "v${{ inputs.release-version }} release" \
            --generate-notes \
            ${TAG} \
            ${WINDOWS_RELEASE_APPLICATION_ZIP}
